"""Write data/career_graph.json as a plain Cypher script you can paste into the
Aura console (Query tab) or Neo4j Browser, for when you can't run scripts.seed.

    python -m scripts.export_cypher > seed.cypher

The script replaces the graph, like scripts.seed.
"""

from __future__ import annotations

import sys
from pathlib import Path

from app.domain.career_data import CareerDataset, load_career_data
from app.infrastructure.cypher_script import COUNT_STATEMENT, seed_statements

DEFAULT_DATA = Path(__file__).resolve().parent.parent / "data" / "career_graph.json"


def to_cypher(dataset: CareerDataset) -> str:
    header = (
        f"// Career graph: {len(dataset.nodes)} nodes, {len(dataset.relationships)} relationships.\n"
        "// Generated by `python -m scripts.export_cypher`. Replaces everything in the database.\n"
    )
    return header + ";\n\n".join([*seed_statements(dataset), COUNT_STATEMENT]) + ";\n"


def main() -> None:
    path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_DATA
    sys.stdout.write(to_cypher(load_career_data(path)))


if __name__ == "__main__":
    main()
