"""Write data/career_graph.json as a plain Cypher script you can paste into the
Aura console (Query tab) or Neo4j Browser, for when you can't run scripts.seed.

    python -m scripts.export_cypher > seed.cypher

The script replaces the graph, like scripts.seed.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from app.domain import schema
from app.domain.career_data import CareerDataset, load_career_data

DEFAULT_DATA = Path(__file__).resolve().parent.parent / "data" / "career_graph.json"


def _literal(value: Any) -> str:
    """Render a JSON value as a Cypher literal. json.dumps' escaping is valid Cypher string syntax."""
    if isinstance(value, dict):
        return "{" + ", ".join(f"{key}: {_literal(v)}" for key, v in value.items()) + "}"
    if isinstance(value, list):
        return "[" + ", ".join(_literal(v) for v in value) + "]"
    return json.dumps(value, ensure_ascii=True)


def to_cypher(dataset: CareerDataset) -> str:
    statements = [
        f"CREATE CONSTRAINT {t.label.lower()}_id IF NOT EXISTS FOR (n:{t.label}) REQUIRE n.id IS UNIQUE"
        for t in schema.NODE_TYPES
    ]
    statements.append("MATCH (n) DETACH DELETE n")

    for label, rows in dataset.nodes_by_label().items():
        statements.append(f"UNWIND {_literal(rows)} AS row\nCREATE (n:{label}) SET n = row")

    label_of = {node.id: node.label for node in dataset.nodes}
    grouped: dict[tuple[str, str, str], list[dict[str, str]]] = {}
    for rel in dataset.relationships:
        key = (rel.type, label_of[rel.source], label_of[rel.target])
        grouped.setdefault(key, []).append({"source": rel.source, "target": rel.target})
    for (rel_type, source_label, target_label), rows in grouped.items():
        statements.append(
            f"UNWIND {_literal(rows)} AS row\n"
            f"MATCH (a:{source_label} {{id: row.source}})\n"
            f"MATCH (b:{target_label} {{id: row.target}})\n"
            f"CREATE (a)-[:{rel_type}]->(b)"
        )

    statements.append("MATCH (n) WITH count(n) AS nodes MATCH ()-[r]->() RETURN nodes, count(r) AS relationships")
    header = (
        f"// Career graph: {len(dataset.nodes)} nodes, {len(dataset.relationships)} relationships.\n"
        "// Generated by `python -m scripts.export_cypher`. Replaces everything in the database.\n"
    )
    return header + ";\n\n".join(statements) + ";\n"


def main() -> None:
    path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_DATA
    sys.stdout.write(to_cypher(load_career_data(path)))


if __name__ == "__main__":
    main()
